[package]
name = "foermchen"
version = "0.1.0"
authors = ["Jan-Lukas Wynen <j-l.wynen@hotmail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unic-ucd-ident = "0.9"
